import { chromium } from '@playwright/test';
import { mkdir } from 'node:fs/promises';
import assert from 'node:assert/strict';
const dir = new URL('../.impeccable/review/', import.meta.url).pathname;
await mkdir(dir,{recursive:true});
const browser=await chromium.launch({channel:'chrome',headless:true});
try {
 const page=await browser.newPage({viewport:{width:1440,height:1000}});
 const errors=[];page.on('pageerror',e=>errors.push(e.message)); page.setDefaultTimeout(20000);
 await page.goto(process.env.APP_URL || 'http://127.0.0.1:4323', { waitUntil: 'domcontentloaded' });
 await page.getByRole('button',{name:'Mary Balogh',exact:true}).waitFor({timeout:30000});
 await page.getByText('Connected to Google Sheets',{exact:true}).waitFor();
 await page.waitForTimeout(4500);
 await page.screenshot({path:dir+'/desktop.png',fullPage:true});
 console.log('authors',await page.locator('.rankings.numbered').innerText());
 assert.equal(await page.getByText('B.K. Borison',{exact:true}).count(),0);
 assert.equal(await page.getByText('Same books.',{exact:false}).count(),0);
 assert.equal(await page.getByText('Books finished each month',{exact:true}).count(),0);
 await page.getByRole('button',{name:'Kelsie Hoss',exact:true}).click();
 assert.equal(await page.locator('.book-tile').count(),8);
 await page.getByRole('button',{name:'To be read',exact:false}).click();
 assert.equal(await page.locator('.book-tile').count(),15);
 await page.getByRole('searchbox',{name:'Search books'}).fill('Lisa Kleypas');
 assert.equal(await page.locator('.book-tile').count(),4);
 await page.getByRole('button',{name:'Series',exact:true}).click();
 await page.getByRole('searchbox',{name:'Search series'}).fill('Spoiler Alert');
 assert.ok((await page.locator('.series-grid').innerText()).includes('numbering differs'));
 await page.getByRole('button',{name:'Overview',exact:true}).click();
 await page.getByLabel('Reading year').selectOption('2025');
 assert.notEqual(await page.locator('.summary strong').first().innerText(),'68');
 await page.getByLabel('Reading year').selectOption('2026');
 await page.setViewportSize({width:390,height:844});
 await page.evaluate(async () => { window.scrollTo(0, 0); await document.fonts.ready; });
 await page.waitForTimeout(250);
 await page.screenshot({path:dir+'/mobile.png',fullPage:true});
 assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);
 await page.setViewportSize({width:1536,height:1024});
 await page.evaluate(async () => { window.scrollTo(0, 0); await document.fonts.ready; });
 await page.waitForTimeout(250);
 await page.screenshot({path:dir+'/hero-repro.png'});
 assert.deepEqual(errors,[]);
 console.log('PASS: live author data, removed copy, author filter, TBR15/search4, series conflict, year filter, mobile overflow, browser errors');
} finally {await browser.close();}
